#!/bin/sh

# install vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# install color theme
config_dir="$(dirname "$(realpath "$0")")"
doas cp "$config_dir/termcolors.vim" "/usr/share/nvim/runtime/colors/"
